stages:
  - build
  - test
  - scan-external
  - scan-internal
  - pages

build:
  stage: build
  tags:
    - shell
  script:
    - make build

test:
  stage: test
  tags:
    - shell
  before_script:
    - make env
  script:
    - make test
  after_script:
    - make env-stop
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 1 days
  coverage: '/total\:\s*\(statements\)\s*\d{1,}\.\d\%/'

scan-external:
  stage: scan-external
  tags:
    - shell-luiz
  before_script:
    - pip install scanapi==2.1.0
  script:
    - make scan-external
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 1 days

scan-internal:
  stage: scan-internal
  tags:
    - shell-luiz
  before_script:
    - pip install scanapi==2.1.0
    - make env
    - make build
    - make image
    - make run-docker
  script:
    - make scan-internal
  after_script:
    - make env-stop
    - make remove-docker
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 1 days

pages:
  stage: pages
  tags:
    - shell
  dependencies:
    - test
    - scan-external
    - scan-internal
  script:
    - mkdir public
    - mv coverage/ public/
  artifacts:
    untracked: true
    when: always
    paths:
      - public
    expire_in: 360 days
