// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "github.com/companies/internal/core/entities"
	mock "github.com/stretchr/testify/mock"
)

// CompanyInserter is an autogenerated mock type for the CompanyInserter type
type CompanyInserter struct {
	mock.Mock
}

// AddCompany provides a mock function with given fields: company
func (_m *CompanyInserter) AddCompany(company *entities.Company) (*entities.Company, error) {
	ret := _m.Called(company)

	var r0 *entities.Company
	if rf, ok := ret.Get(0).(func(*entities.Company) *entities.Company); ok {
		r0 = rf(company)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Company)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entities.Company) error); ok {
		r1 = rf(company)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
